### ISSUE TITLE
Does not work, maybe Python 2.7?

### ISSUE THREAD

**Issue by demkinmaxim** [deviantony/xtrabackup-scripts#14]
Unfortunately, script does not work :(
```
/usr/bin/pyxtrabackup-inc /var/backup/mysql/data --incremental --user=root --log-file=/var/backup/mysql/backup.log
ERROR:xtrabackup.incremental_backup:pyxtrabackup failed.
```
Centos 7.0, Python 2.7.5, Percona MySQL 5.6, Xtrabackup 2.2.7
Could it be just because of older Python?

**Comment by demkinmaxim** [comment]
Oops, I've found the reason.
It works :)
Strangely the `/var/backup/mysql/data` was a file, but not a directory.
Made it an empty directory and everything is ok.

**Comment by deviantony** [comment]
Ok I'll close the issue.

Also, always have a look at the file */var/log/mysql/xtrabackup.out* to check the innobackupex process logs for more info ;)
