### ISSUE TITLE
AttributeError: BackupTool instance has no attribute 'final_archive_path'

### ISSUE THREAD

**Issue by gorpet** [deviantony/xtrabackup-scripts#15]
There is a problem in your code doing base for incremental backup:

$ pyxtrabackup-inc <PATH TO REPOSITORY> --user=<MYSQL USER> [ --password=<MYSQL PASSWORD> ]

As you can see in backup_tools.py on line #202 there is no call for "self.prepare_archive_name(incremental, True)" method, which is the only place setting self.final_archive_path variable which is then used and needed later in self.transfer_backup method.

Not setting final_archive_path variable in case of doing base for incremental backups results in failed backup:

INFO:xtrabackup.backup_tools:Backup time: 0:11:26.153863 - Duration: 686
INFO:xtrabackup.backup_tools:Backup compression time: 0:20:10.222072 - Duration: 1210
ERROR:xtrabackup.backup_tools:An error occured during the backup compression.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/xtrabackup/backup_tools.py", line 125, in transfer_backup
    self.logger.debug("Archive path: " + self.final_archive_path)
AttributeError: BackupTool instance has no attribute 'final_archive_path'
ERROR:xtrabackup.incremental_backup:pyxtrabackup failed.

Suggested fix would be to include line:

"self.prepare_archive_name(incremental, True)"

before "self.exec_full_backup(user, password, threads)" on #202.

Regards,
Goran Petanjek

**Comment by deviantony** [comment]
Thanks for the report !
