### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by timk95** [deviantony/xtrabackup-scripts#22]
MariaDB lacks of bitmap-based incremental backup support and gives an error with incremental backups.

I've Googled for a workaround and found that passing the **--incremental-force-scan** flag with the incremental backup command makes MariaDB working with XtraBackup.

I've fixed this for myself by adding this flag in the **exec_incremental_backup** function. Might be worth adding this flag for future releases.

**Comment by deviantony** [comment]
Merged ! Thanks @timk95 

:+1:
